package cn.edu.guet.entity;

import org.springframework.context.annotation.Bean;

import java.sql.Timestamp;
import java.util.Date;

public class Bxd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.sbsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Timestamp sbsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.eid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.xxdd
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xxdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.yysj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String yysj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.bxlb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String bxlb;

    private Integer dict_id;
    private String dictitem_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.bxnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String bxnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.sp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.tp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String tp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.sbr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.shy1state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer shy1state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.sbrxh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sbrxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.hc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String hc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.gs
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String gs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.jid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String jid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.shy1
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String shy1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.sbrsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sbrsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.shy2
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String shy2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.shy2state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer shy2state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.wxsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date wxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.cxsy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String cxsy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.pj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String pj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.pjnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String pjnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.pjzj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String pjzj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.fgts
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer fgts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.jdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date jdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxd.yssj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date yssj;

    private String dict_description;

    private String ditem_value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.id
     *
     * @return the value of bxd.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.id
     *
     * @param id the value for bxd.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.sbsj
     *
     * @return the value of bxd.sbsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getSbsj() {
        return sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.sbsj
     *
     * @param sbsj the value for bxd.sbsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSbsj(Timestamp sbsj) {
        this.sbsj = sbsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.eid
     *
     * @return the value of bxd.eid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.eid
     *
     * @param eid the value for bxd.eid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.xxdd
     *
     * @return the value of bxd.xxdd
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXxdd() {
        return xxdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.xxdd
     *
     * @param xxdd the value for bxd.xxdd
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXxdd(String xxdd) {
        this.xxdd = xxdd == null ? null : xxdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.yysj
     *
     * @return the value of bxd.yysj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getYysj() {
        return yysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.yysj
     *
     * @param yysj the value for bxd.yysj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYysj(String yysj) {
        this.yysj = yysj == null ? null : yysj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.bxlb
     *
     * @return the value of bxd.bxlb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getBxlb() {
        return bxlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.bxlb
     *
     * @param bxlb the value for bxd.bxlb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setBxlb(String bxlb) {
        this.bxlb = bxlb == null ? null : bxlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.bxnr
     *
     * @return the value of bxd.bxnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getBxnr() {
        return bxnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.bxnr
     *
     * @param bxnr the value for bxd.bxnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setBxnr(String bxnr) {
        this.bxnr = bxnr == null ? null : bxnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.sp
     *
     * @return the value of bxd.sp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSp() {
        return sp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.sp
     *
     * @param sp the value for bxd.sp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSp(String sp) {
        this.sp = sp == null ? null : sp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.tp
     *
     * @return the value of bxd.tp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getTp() {
        return tp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.tp
     *
     * @param tp the value for bxd.tp
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTp(String tp) {
        this.tp = tp == null ? null : tp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.sbr
     *
     * @return the value of bxd.sbr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSbr() {
        return sbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.sbr
     *
     * @param sbr the value for bxd.sbr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSbr(String sbr) {
        this.sbr = sbr == null ? null : sbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.shy1state
     *
     * @return the value of bxd.shy1state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getShy1state() {
        return shy1state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.shy1state
     *
     * @param shy1state the value for bxd.shy1state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setShy1state(Integer shy1state) {
        this.shy1state = shy1state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.sbrxh
     *
     * @return the value of bxd.sbrxh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSbrxh() {
        return sbrxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.sbrxh
     *
     * @param sbrxh the value for bxd.sbrxh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSbrxh(String sbrxh) {
        this.sbrxh = sbrxh == null ? null : sbrxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.hc
     *
     * @return the value of bxd.hc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getHc() {
        return hc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.hc
     *
     * @param hc the value for bxd.hc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setHc(String hc) {
        this.hc = hc == null ? null : hc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.gs
     *
     * @return the value of bxd.gs
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getGs() {
        return gs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.gs
     *
     * @param gs the value for bxd.gs
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setGs(String gs) {
        this.gs = gs == null ? null : gs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.jid
     *
     * @return the value of bxd.jid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.jid
     *
     * @param jid the value for bxd.jid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setJid(String jid) {
        this.jid = jid == null ? null : jid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.shy1
     *
     * @return the value of bxd.shy1
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getShy1() {
        return shy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.shy1
     *
     * @param shy1 the value for bxd.shy1
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setShy1(String shy1) {
        this.shy1 = shy1 == null ? null : shy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.sbrsj
     *
     * @return the value of bxd.sbrsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSbrsj() {
        return sbrsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.sbrsj
     *
     * @param sbrsj the value for bxd.sbrsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSbrsj(String sbrsj) {
        this.sbrsj = sbrsj == null ? null : sbrsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.shy2
     *
     * @return the value of bxd.shy2
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getShy2() {
        return shy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.shy2
     *
     * @param shy2 the value for bxd.shy2
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setShy2(String shy2) {
        this.shy2 = shy2 == null ? null : shy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.shy2state
     *
     * @return the value of bxd.shy2state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getShy2state() {
        return shy2state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.shy2state
     *
     * @param shy2state the value for bxd.shy2state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setShy2state(Integer shy2state) {
        this.shy2state = shy2state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.wxsj
     *
     * @return the value of bxd.wxsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getWxsj() {
        return wxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.wxsj
     *
     * @param wxsj the value for bxd.wxsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setWxsj(Date wxsj) {
        this.wxsj = wxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.cxsy
     *
     * @return the value of bxd.cxsy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getCxsy() {
        return cxsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.cxsy
     *
     * @param cxsy the value for bxd.cxsy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setCxsy(String cxsy) {
        this.cxsy = cxsy == null ? null : cxsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.pj
     *
     * @return the value of bxd.pj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getPj() {
        return pj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.pj
     *
     * @param pj the value for bxd.pj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setPj(String pj) {
        this.pj = pj == null ? null : pj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.pjnr
     *
     * @return the value of bxd.pjnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getPjnr() {
        return pjnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.pjnr
     *
     * @param pjnr the value for bxd.pjnr
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setPjnr(String pjnr) {
        this.pjnr = pjnr == null ? null : pjnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.pjzj
     *
     * @return the value of bxd.pjzj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getPjzj() {
        return pjzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.pjzj
     *
     * @param pjzj the value for bxd.pjzj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setPjzj(String pjzj) {
        this.pjzj = pjzj == null ? null : pjzj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.state
     *
     * @return the value of bxd.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.state
     *
     * @param state the value for bxd.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.fgts
     *
     * @return the value of bxd.fgts
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getFgts() {
        return fgts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.fgts
     *
     * @param fgts the value for bxd.fgts
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setFgts(Integer fgts) {
        this.fgts = fgts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.jdsj
     *
     * @return the value of bxd.jdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getJdsj() {
        return jdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.jdsj
     *
     * @param jdsj the value for bxd.jdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setJdsj(Date jdsj) {
        this.jdsj = jdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxd.yssj
     *
     * @return the value of bxd.yssj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getYssj() {
        return yssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxd.yssj
     *
     * @param yssj the value for bxd.yssj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYssj(Date yssj) {
        this.yssj = yssj;
    }

    public void setDict_id(Integer dict_id) {
        this.dict_id = dict_id;
    }

    public void setDictitem_id(String dictitem_id) {
        this.dictitem_id = dictitem_id;
    }

    public void setDict_description(String dict_description) {
        this.dict_description = dict_description;
    }

    public void setDitem_value(String ditem_value) {
        this.ditem_value = ditem_value;
    }

    public Integer getDict_id() {
        return dict_id;
    }

    public String getDictitem_id() {
        return dictitem_id;
    }

    public String getDict_description() {
        return dict_description;
    }

    public String getDitem_value() {
        return ditem_value;
    }
}