package cn.edu.guet.entity;

public class Bxqy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.qy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String qy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.qylb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String qylb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bxqy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.id
     *
     * @return the value of bxqy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.id
     *
     * @param id the value for bxqy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.qy
     *
     * @return the value of bxqy.qy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getQy() {
        return qy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.qy
     *
     * @param qy the value for bxqy.qy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setQy(String qy) {
        this.qy = qy == null ? null : qy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.qylb
     *
     * @return the value of bxqy.qylb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getQylb() {
        return qylb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.qylb
     *
     * @param qylb the value for bxqy.qylb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setQylb(String qylb) {
        this.qylb = qylb == null ? null : qylb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.xq
     *
     * @return the value of bxqy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.xq
     *
     * @param xq the value for bxqy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.x
     *
     * @return the value of bxqy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.x
     *
     * @param x the value for bxqy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bxqy.y
     *
     * @return the value of bxqy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bxqy.y
     *
     * @param y the value for bxqy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setY(String y) {
        this.y = y == null ? null : y.trim();
    }
}