package cn.edu.guet.entity;

public class Cet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.examid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.allgrade
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer allgrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.lisen
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer lisen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.read
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer read;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.write
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer write;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cet.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.id
     *
     * @return the value of cet.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.id
     *
     * @param id the value for cet.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.sid
     *
     * @return the value of cet.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.sid
     *
     * @param sid the value for cet.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.name
     *
     * @return the value of cet.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.name
     *
     * @param name the value for cet.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.examid
     *
     * @return the value of cet.examid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.examid
     *
     * @param examid the value for cet.examid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setExamid(String examid) {
        this.examid = examid == null ? null : examid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.allgrade
     *
     * @return the value of cet.allgrade
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getAllgrade() {
        return allgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.allgrade
     *
     * @param allgrade the value for cet.allgrade
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setAllgrade(Integer allgrade) {
        this.allgrade = allgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.lisen
     *
     * @return the value of cet.lisen
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getLisen() {
        return lisen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.lisen
     *
     * @param lisen the value for cet.lisen
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setLisen(Integer lisen) {
        this.lisen = lisen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.read
     *
     * @return the value of cet.read
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.read
     *
     * @param read the value for cet.read
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.write
     *
     * @return the value of cet.write
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getWrite() {
        return write;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.write
     *
     * @param write the value for cet.write
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setWrite(Integer write) {
        this.write = write;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cet.time
     *
     * @return the value of cet.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cet.time
     *
     * @param time the value for cet.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}