package cn.edu.guet.entity;

public class Hc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.mc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String mc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.jg
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Double jg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.dw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String dw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.kc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer kc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.lb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String lb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hc.xh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.id
     *
     * @return the value of hc.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.id
     *
     * @param id the value for hc.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.mc
     *
     * @return the value of hc.mc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.mc
     *
     * @param mc the value for hc.mc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.jg
     *
     * @return the value of hc.jg
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Double getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.jg
     *
     * @param jg the value for hc.jg
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setJg(Double jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.dw
     *
     * @return the value of hc.dw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getDw() {
        return dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.dw
     *
     * @param dw the value for hc.dw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setDw(String dw) {
        this.dw = dw == null ? null : dw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.kc
     *
     * @return the value of hc.kc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getKc() {
        return kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.kc
     *
     * @param kc the value for hc.kc
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setKc(Integer kc) {
        this.kc = kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.lb
     *
     * @return the value of hc.lb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.lb
     *
     * @param lb the value for hc.lb
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hc.xh
     *
     * @return the value of hc.xh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hc.xh
     *
     * @param xh the value for hc.xh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }
}