package cn.edu.guet.entity;

public class Jdr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String ybid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String gh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.sj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.yx
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String yx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdr.ywfw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String ywfw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.ybid
     *
     * @return the value of jdr.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getYbid() {
        return ybid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.ybid
     *
     * @param ybid the value for jdr.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYbid(String ybid) {
        this.ybid = ybid == null ? null : ybid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.gh
     *
     * @return the value of jdr.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getGh() {
        return gh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.gh
     *
     * @param gh the value for jdr.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setGh(String gh) {
        this.gh = gh == null ? null : gh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.xm
     *
     * @return the value of jdr.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.xm
     *
     * @param xm the value for jdr.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.sj
     *
     * @return the value of jdr.sj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.sj
     *
     * @param sj the value for jdr.sj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.yx
     *
     * @return the value of jdr.yx
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getYx() {
        return yx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.yx
     *
     * @param yx the value for jdr.yx
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYx(String yx) {
        this.yx = yx == null ? null : yx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.state
     *
     * @return the value of jdr.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.state
     *
     * @param state the value for jdr.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdr.ywfw
     *
     * @return the value of jdr.ywfw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getYwfw() {
        return ywfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdr.ywfw
     *
     * @param ywfw the value for jdr.ywfw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYwfw(String ywfw) {
        this.ywfw = ywfw == null ? null : ywfw.trim();
    }
}