package cn.edu.guet.entity;

import java.util.Date;

public class Qdb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qdb.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qdb.qdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date qdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qdb.shyid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String shyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qdb.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qdb.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qdb.id
     *
     * @return the value of qdb.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qdb.id
     *
     * @param id the value for qdb.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qdb.qdsj
     *
     * @return the value of qdb.qdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getQdsj() {
        return qdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qdb.qdsj
     *
     * @param qdsj the value for qdb.qdsj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setQdsj(Date qdsj) {
        this.qdsj = qdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qdb.shyid
     *
     * @return the value of qdb.shyid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getShyid() {
        return shyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qdb.shyid
     *
     * @param shyid the value for qdb.shyid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setShyid(String shyid) {
        this.shyid = shyid == null ? null : shyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qdb.xq
     *
     * @return the value of qdb.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qdb.xq
     *
     * @param xq the value for qdb.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qdb.state
     *
     * @return the value of qdb.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qdb.state
     *
     * @param state the value for qdb.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }
}