package cn.edu.guet.entity;

import java.util.Date;

public class QmBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_book.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_book.title
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_book.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_book.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_book.id
     *
     * @return the value of qm_book.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_book.id
     *
     * @param id the value for qm_book.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_book.title
     *
     * @return the value of qm_book.title
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_book.title
     *
     * @param title the value for qm_book.title
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_book.time
     *
     * @return the value of qm_book.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_book.time
     *
     * @param time the value for qm_book.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_book.xq
     *
     * @return the value of qm_book.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_book.xq
     *
     * @param xq the value for qm_book.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }
}