package cn.edu.guet.entity;

import java.util.Date;

public class QmCanvas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.bid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.xy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.zy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String bj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.pic
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qm_canvas.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.id
     *
     * @return the value of qm_canvas.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.id
     *
     * @param id the value for qm_canvas.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.bid
     *
     * @return the value of qm_canvas.bid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.bid
     *
     * @param bid the value for qm_canvas.bid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.sid
     *
     * @return the value of qm_canvas.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.sid
     *
     * @param sid the value for qm_canvas.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.name
     *
     * @return the value of qm_canvas.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.name
     *
     * @param name the value for qm_canvas.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.xy
     *
     * @return the value of qm_canvas.xy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXy() {
        return xy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.xy
     *
     * @param xy the value for qm_canvas.xy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXy(String xy) {
        this.xy = xy == null ? null : xy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.zy
     *
     * @return the value of qm_canvas.zy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.zy
     *
     * @param zy the value for qm_canvas.zy
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.bj
     *
     * @return the value of qm_canvas.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.bj
     *
     * @param bj the value for qm_canvas.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setBj(String bj) {
        this.bj = bj == null ? null : bj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.pic
     *
     * @return the value of qm_canvas.pic
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.pic
     *
     * @param pic the value for qm_canvas.pic
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qm_canvas.time
     *
     * @return the value of qm_canvas.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qm_canvas.time
     *
     * @param time the value for qm_canvas.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }
}