package cn.edu.guet.entity;

public class Shy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String ybid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String gh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.zw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer zw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.ybid
     *
     * @return the value of shy.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getYbid() {
        return ybid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.ybid
     *
     * @param ybid the value for shy.ybid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setYbid(String ybid) {
        this.ybid = ybid == null ? null : ybid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.gh
     *
     * @return the value of shy.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getGh() {
        return gh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.gh
     *
     * @param gh the value for shy.gh
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setGh(String gh) {
        this.gh = gh == null ? null : gh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.xm
     *
     * @return the value of shy.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.xm
     *
     * @param xm the value for shy.xm
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.zw
     *
     * @return the value of shy.zw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.zw
     *
     * @param zw the value for shy.zw
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setZw(Integer zw) {
        this.zw = zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.xq
     *
     * @return the value of shy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.xq
     *
     * @param xq the value for shy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.x
     *
     * @return the value of shy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.x
     *
     * @param x the value for shy.x
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shy.y
     *
     * @return the value of shy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shy.y
     *
     * @param y the value for shy.y
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setY(String y) {
        this.y = y == null ? null : y.trim();
    }
}