package cn.edu.guet.entity;

import java.util.Date;

public class Xlyy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.one
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.two
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.phone
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String xq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String bj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xlyy.ly
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    private String ly;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.id
     *
     * @return the value of xlyy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.id
     *
     * @param id the value for xlyy.id
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.name
     *
     * @return the value of xlyy.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.name
     *
     * @param name the value for xlyy.name
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.sid
     *
     * @return the value of xlyy.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.sid
     *
     * @param sid the value for xlyy.sid
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.one
     *
     * @return the value of xlyy.one
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.one
     *
     * @param one the value for xlyy.one
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setOne(String one) {
        this.one = one == null ? null : one.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.two
     *
     * @return the value of xlyy.two
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.two
     *
     * @param two the value for xlyy.two
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTwo(String two) {
        this.two = two == null ? null : two.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.phone
     *
     * @return the value of xlyy.phone
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.phone
     *
     * @param phone the value for xlyy.phone
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.time
     *
     * @return the value of xlyy.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.time
     *
     * @param time the value for xlyy.time
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.state
     *
     * @return the value of xlyy.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.state
     *
     * @param state the value for xlyy.state
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.xq
     *
     * @return the value of xlyy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getXq() {
        return xq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.xq
     *
     * @param xq the value for xlyy.xq
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setXq(String xq) {
        this.xq = xq == null ? null : xq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.bj
     *
     * @return the value of xlyy.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.bj
     *
     * @param bj the value for xlyy.bj
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setBj(String bj) {
        this.bj = bj == null ? null : bj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xlyy.ly
     *
     * @return the value of xlyy.ly
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public String getLy() {
        return ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xlyy.ly
     *
     * @param ly the value for xlyy.ly
     *
     * @mbg.generated Fri Aug 27 11:25:46 CST 2021
     */
    public void setLy(String ly) {
        this.ly = ly == null ? null : ly.trim();
    }
}