server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glmc?dormitory=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: chenyicai
    password: cyc1234
logging:
  level:
    cn:
      edu:
        guet:
          mapper: debug

mybatis:
  type-aliases-package: cn.edu.guet.entity
  mapper-locations: classpath:mapper/*.xml

